//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchange.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convertation
    {
        public int ConvertationId { get; set; }
        public string BuyingCurrency { get; set; }
        public string SellingCurency { get; set; }
        public double AmountReceived { get; set; }
        public double AmountReturned { get; set; }
        public System.DateTime ConvertationDate { get; set; }
        public string ConverationComment { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
